site:
  name: SERENA
  site: 'https://www.serenafelix.cc'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: SERENA
    template: '%s â€” SERENA'
  description: 'SERENA provides clarity, answers, and guidance through intuitive prompts and personalized insights.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: SERENA
    images:
      - url: '~/assets/images/serena/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@serena'
    site: '@serena'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
